create table CUSTOMER (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  normalized VARCHAR(512) NOT NULL,
  email_address VARCHAR(255) NOT NULL
);
create table ADDRESS (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
  customer_id BIGINT CONSTRAINT address_customer_ref REFERENCES CUSTOMER (id),
  street VARCHAR(255) NOT NULL,
  city VARCHAR(255) NOT NULL,
  country VARCHAR(3) NOT NULL
);
create table PRODUCT (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description CLOB(1024),
  price INTEGER NOT NULL CHECK (price >= 0)
);
create table ORDER_ITEM (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
  product_id BIGINT CONSTRAINT order_item_product_ref REFERENCES PRODUCT (id),
  quantity INTEGER NOT NULL CHECK (quantity > 0),
  price INTEGER NOT NULL CHECK (price >= 0)
);
create table ORDERING (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
  customer_id BIGINT CONSTRAINT ordering_customer_ref REFERENCES CUSTOMER (id),
  shipping_address_id  BIGINT CONSTRAINT ordering_shipping_ref REFERENCES ADDRESS (id),
  billing_address_id  BIGINT CONSTRAINT ordering_billing_ref REFERENCES ADDRESS (id) NOT NULL,
  status SMALLINT NOT NULL,
  order_date TIMESTAMP NOT NULL
);
create table ORDERING_ITEMS (
 order_id BIGINT CONSTRAINT ordering_items_ordering_ref REFERENCES ORDERING (id),
 item_id BIGINT CONSTRAINT ordering_items_item_ref REFERENCES ORDER_ITEM (id)
);
